apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  labels:
    app.kubernetes.io/name: http-echo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: http-echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-echo
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:latest
          ports:
            - containerPort: 5678
              name: http
              protocol: TCP
