name: validate

on:
  - pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: validate github actions yaml
        run: yamllint .github/
      - name: validate deploy yaml
        run: yamllint deploy/
      - name: validate bootstrap kustomize
        run: kustomize build deploy/bootstrap
      - name: validate http-echo kustomize
        run: kustomize build deploy/apps/http-echo/overlays/dev
