name: validate

on:
  push:
    branches:
      - main

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML file
        run: yamllint deploy/
      - name: valid kustomize bootstrap
        run: kustomize build deploy/bootstrap
      - name: valid kustomize http-echo
        run: kustomize build deploy/apps/http-echo/overlays/dev
